
my:
  property:
    name: "Hello, world!"

#CONFIG trong DEV

spring:
  profiles:
    include: common, ex,local

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'

  main:
    allow-bean-definition-overriding: 'true'


#CONFIG FOR EXAMPLE SCOPE

server:
  session:
    timeout: '1'
    cookie:
      max-age: '1'

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE


#


